### ISSUE TITLE
env variables validation

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Schedule-RTU-Bot#2]
Добавить валидацию переменных окружения, чтобы при их отсутствии приложение не выпадало на 404 от телеграма, а падало само, с осознанными сообщениями об ошибке

**Comment by Delivery-Klad** [comment]
![image](https://user-images.githubusercontent.com/49003989/118656584-566f4200-b7f3-11eb-897b-7911c14c9f8f.png)

**Comment by Delivery-Klad** [comment]
с хероку

**Comment by CAPCHIK** [comment]
Осознал
