### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Schedule-RTU-Bot#3]
Добавить логирование.

Как минимум - сообщение о том, что созданы таблицы, что приложение запущено, работает под ботом с таким-то id, и так далее.

Без логов вовсе не ясно, запустилось приложение, или нет

**Comment by Delivery-Klad** [comment]
![image](https://user-images.githubusercontent.com/49003989/118655977-bdd8c200-b7f2-11eb-9e9c-d6ea469c0884.png)
Под каким id запущен бот появлялось и до этого

**Comment by CAPCHIK** [comment]
Боюсь, нет. Позже опишу как воспроизвести

**Comment by CAPCHIK** [comment]
Забыл про буферизацию вывода в питоне, вместе с 97f3477ca1606fe8383de769acb473f6d873fd88 работает
